[workspace]
members = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
]

[profile.release]
lto="fat"
codegen-units=1
panic="abort"

[profile.bench]
lto="fat"
codegen-units=1
panic="abort"